FROM gcc:9

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y git make autoconf automake libtool pkg-config

COPY . .

RUN ./autogen.sh && \
    ./configure && \
    make

# Default command runs make check
CMD ["make", "check"]