FROM ubuntu:focal

# 避免在安装过程中出现交互式提示
ENV DEBIAN_FRONTEND=noninteractive

# 安装构建依赖项和开发工具
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
        cmake \
        ninja-build \
        build-essential \
        ccache \
        git \
        vim \
        gdb \
        valgrind \
        clang \
        clang-tools \
        clang-format \
        && \
    rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 复制源代码到容器中
COPY . .

# 创建构建目录并进入
WORKDIR /app/build

# 配置CMake项目
RUN cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release

# 构建项目
RUN cmake --build . -- -j$(nproc)

# 设置默认命令运行测试
CMD ["./nb"]